# Generated by Django 5.0.6 on 2025-09-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('report', 'Rapor'), ('checkup', 'Kontrol')], max_length=10)),
                ('appointment_status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=10)),
                ('serial_number', models.CharField(max_length=10, unique=True)),
                ('payment_status', models.CharField(default='pending', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Doctor_Information',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Erkek'), ('female', 'Kadın')], max_length=10)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('department_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('featured_image', models.ImageField(default='doctors/user-default.png', upload_to='doctors/')),
                ('certificate_image', models.ImageField(default='doctors_certificate/default.png', upload_to='doctors_certificate/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('nid', models.CharField(max_length=11, unique=True)),
                ('visiting_hour', models.CharField(max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dob', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('year_of_completion', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_place_name', models.CharField(max_length=200)),
                ('from_year', models.PositiveIntegerField()),
                ('to_year', models.PositiveIntegerField(blank=True, null=True)),
                ('designation', models.CharField(max_length=200)),
                ('currently_working', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicines', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
