# Generated by Django 5.0.6 on 2025-09-13 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='hospital.user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='hospital.user')),
            ],
            options={
                'ordering': ['date_created'],
                'indexes': [models.Index(fields=['user_from', 'user_to'], name='ChatApp_cha_user_fr_a13a8a_idx'), models.Index(fields=['date_created'], name='ChatApp_cha_date_cr_7966f6_idx')],
            },
        ),
    ]
