# Generated by Django 5.0.6 on 2025-09-13 19:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Information',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Hospital ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('featured_image', models.ImageField(default='hospitals/default.png', upload_to='hospitals/', verbose_name='Featured Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('hospital_type', models.CharField(choices=[('private', 'Private Hospital'), ('public', 'Public Hospital')], max_length=10, verbose_name='Hospital Type')),
                ('general_bed_no', models.PositiveIntegerField(default=0, verbose_name='General Beds')),
                ('available_icu_no', models.PositiveIntegerField(default=0, verbose_name='Available ICU Beds')),
                ('regular_cabin_no', models.PositiveIntegerField(default=0, verbose_name='Regular Cabins')),
                ('emergency_cabin_no', models.PositiveIntegerField(default=0, verbose_name='Emergency Cabins')),
                ('vip_cabin_no', models.PositiveIntegerField(default=0, verbose_name='VIP Cabins')),
            ],
            options={
                'verbose_name': 'Hospital Information',
                'verbose_name_plural': 'Hospital Information',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_patient', models.BooleanField(default=False, verbose_name='Patient')),
                ('is_doctor', models.BooleanField(default=False, verbose_name='Doctor')),
                ('is_hospital_admin', models.BooleanField(default=False, verbose_name='Hospital Admin')),
                ('is_labworker', models.BooleanField(default=False, verbose_name='Lab Worker')),
                ('is_pharmacist', models.BooleanField(default=False, verbose_name='Pharmacist')),
                ('login_status', models.BooleanField(default=False, verbose_name='Login Status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='hospital_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='hospital_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Patient ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Username')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('featured_image', models.ImageField(default='patients/user-default.png', upload_to='patients/', verbose_name='Featured Image')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Blood Group')),
                ('medical_history', models.TextField(blank=True, verbose_name='Medical History')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('nid', models.CharField(max_length=20, unique=True, verbose_name='National ID')),
                ('serial_number', models.CharField(max_length=10, unique=True, verbose_name='Serial Number')),
                ('login_status', models.CharField(default='offline', max_length=10, verbose_name='Login Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='hospital.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
